project:
  type: website
  output-dir: docs
website:
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: false
  navbar:
    pinned: true
    collapse: false
    title: false
    background: light
    left:
      - href: index.qmd
        text: Overview
      - href: fastq.qmd
        text: FASTQ+
      - href: PISA.qmd
        text: PISA
      - href: Yano.qmd
        text: Yano
    tools: 
      - icon: github
        text: GitHub
        menu:
          - text: My GitHub Page
            href: https://github.com/shiquan
          - text: Discussions
            href: https://github.com/shiquan/Yano/discussions
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Workflows & Short cases"
        contents:
          - text: "From FASTQ to counts"
            href: workflow1.Rmd
          - text: "Annotate various features"
            href: anno.Rmd
          - text: "Alternative splicing analysis"
            href: Yano_AS.Rmd
          - text: "Allele-specific gene expression analysis"
            href: Yano_ASE.Rmd
          - text: "Annotating genetic variants"
            href: Yano_anno.Rmd
format:
  html:
    theme:
      light: [theme.scss]
      dark: [theme-dark.scss]
    code-copy: true
    css: styles.css
    toc: true
    code-overflow: wrap
    code-block-background: true
    code-block-border-left: true
    page-layout: full
    fontsize: 1.05em
    highlight-style: github
engine: knitr
editor: visual
