---
#page-layout: custom
sidebar: false
section-divs: false
toc: false
css: index.css
editor: source
---
This website outlines the key tools and software packages developed from my research:

<!-- -->

-   **FASTQ+**: This format enhances the standard FASTQ file by integrating barcode information directly into the read name. This modification facilitates the harmonization of single-cell sequencing data across various platforms. FASTQ+ can be generated with PISA.
-   **PISA**: A suite of programs specifically designed for preprocessing data from single-cell sequencing and spatial transcriptomics. It efficiently processes FASTQ+, BAM, and BED files, and generates various feature counts and annotations.
-   **Yano**: An R package that employs the spatial dissimilarity test method as its core algorithm. Yano is tailored for exploring various biological events in single-cell and spatial transcriptomics data, including alternative splicing, allele-specific gene expression, somatic variants and more, providing comprehensive insights into cellular dynamics.
<!--
**dST**: An R package designed for zonation analysis and rankable cell-cell interaction analysis. This package is currently under development.
-->


<strong>Workflows and Short Cases for scRNA-seq and Spatial Transcriptome</strong>

- [From raw reads to gene counts](workflow1.Rmd) (PISA)
- [Annotate various features for alignment](anno.Rmd) (PISA)
- [Alternative splicing analysis for scRNA-seq](Yano_AS.Rmd) (Yano)
- [Allele-specific gene expression analysis for scRNA-seq](Yano_ASE.Rmd) (Yano)
- [Annotating and prioritizing genetic variants for scRNA-seq](Yano_anno.Rmd) (Yano)
- [Perform alternative splicing analysis for multiple Visium samples](Visium.Rmd) (Yano)
- [Select cells from reduction maps and spatial locations](selector.Rmd) (Yano)
- [Perform alternative splicing analysis for cell trajectory and user-defined embeddings](Yano_trajectory.Rmd) (Yano)


  
